version: "3.9"

services:

  postgres:

    image: postgres:16

    container_name: customer-db

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer_ai

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:

    build: .

    container_name: customer-api

    depends_on:
      - postgres

    ports:
      - "8000:8000"

    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      API_KEY: ${API_KEY}
      DATABASE_URL: postgresql://admin:password@postgres:5432/customer_ai

  prometheus:

    image: prom/prometheus

    container_name: prometheus

    depends_on:
      - api

    ports:
      - "9090:9090"

    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:

    image: grafana/grafana

    container_name: grafana

    depends_on:
      - prometheus

    ports:
      - "3000:3000"

    volumes:
      - grafana_data:/var/lib/grafana
volumes:
  postgres_data:
  grafana_data:
